# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: JungEun (Gracie) Kim
title: ''
email: jungeun122333 [AT] kaist.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jungeun122333
github_username:  jungeun122333
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jungeun122333
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: X (Twitter)
  icon: fab fa-twitter
  url: https://x.com/jungeun122333
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=W_8P1eQAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: 
- trackingID: "G-3BD1RQXQHM"
  anonymizeIP: true
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Master's student at [Machine Learning and Intelligence Lab](https://mli.kaist.ac.kr/) (MLILAB) at [KAIST](https://kaist.ac.kr/), advised by [Prof. Eunho Yang](https://scholar.google.com/citations?hl=ko&user=UWO1mloAAAAJ). I received my B.S. in Computer Science and Electrical Engineering from KAIST in 2022.

  My research mainly focuses on Computer Vision, especially on (i) 3D, and (ii) Vision-Language Models.

content:
  - title: News
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Apr 2024**: I will be visiting [Carnegie Mellon University](https://www.cmu.edu/) as a Korean government-sponsored student starting this August. Looking forward to collaborating on projects!
      - **Feb 2024**: [UVI-Net](https://arxiv.org/abs/2404.01464) is accepted to CVPR 2024.

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Data-Efficient Unsupervised Interpolation Without Any Intermediate Frame for 4D Medical Images** <br>
      <u>JungEun Kim</u>\*, Hangyul Yoon\*, Geondo Park, Kyungsu Kim, Eunho Yang <br>
      IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2024 <br>
      [paper](https://arxiv.org/abs/2404.01464) | [code](https://github.com/jungeun122333/UVI-Net)

  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **[Scheduled] Carnegie Mellon University ([CMU](https://www.cmu.edu/))** <br>
      Visiting Student in Computer Science, fully funded by the Korean Government <br>
      Aug. 2024 - Feb. 2025

      - **Korea Advanced Institute of Science and Technology ([KAIST](https://kaist.ac.kr/))** <br>
      Master Student in Artificial Intelligence <br>
      Mar. 2022 - Present

      - **Korea Advanced Institute of Science and Technology ([KAIST](https://kaist.ac.kr/))** <br>
      B.S. in Computer Science and Electrical Engineering (double major) <br>
      Mar. 2017 - Aug. 2022

  - title: Research Experiences
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **[Naver Cloud](https://www.navercloudcorp.com/)** <br>
      Research Intern <br>
      Sep. 2023 - Dec. 2023

      - **[Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/)** <br>
      Research Engineer with Scholarship <br>
      Dec. 2020 - Aug. 2022

      - **KAIST Machine Learning and Intelligence Lab ([MLILAB](https://mli.kaist.ac.kr/))** <br>
      Undergraduate Intern <br>
      Dec. 2020 - Aug. 2022

      - **KAIST Software Engineering Lab ([SELab](https://se.kaist.ac.kr/selab/))** <br>
      Undergraduate Intern <br>
      Mar. 2021 - Nov. 2021

  - title: Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Developing a virtual doctor LLM model, [AITRICS](https://www.aitrics.com/) (2024)
      - Research on the Investigation and Application of Data Augmentation, [Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/) (2022)
      - Investigation and Application of Lightweighting Techniques for Deep Learning Models, [Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/) (2021)
      - An Overview of Gradient Descent Optimization Algorithms with Applications, [Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/) (2021)

  - title: Honors & Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Conference Organizer**, KAIST-Google exploreCSR (2024)
      - **1st Place**, Korea Railroad Research Institute AI Competition (2023)
      - **Leadership Mileage Certificate**, KAIST Global Leadership Center (2022)
      - **Conference Organizer**, National Electronics Major College Student Conference (2020)
      - **Student Council Member**, KAIST Department of Electrical Engineering (2018-2019)
      - **Volunteer Service**: 200+ hours of community service (2015-Present)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
