# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: JungEun (Gracie) Kim
title: ''
email: jungeun122333 [AT] kaist.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jungeun122333
github_username:  jungeun122333
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jungeun122333
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: X (Twitter)
  icon: fab fa-twitter
  url: https://x.com/jungeun122333
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=W_8P1eQAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"
google_analytics_4: "G-3BD1RQXQHM"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Master's student at [Machine Learning and Intelligence Lab](https://mli.kaist.ac.kr/) (MLILAB) at [KAIST](https://kaist.ac.kr/), advised by [Prof. Eunho Yang](https://scholar.google.com/citations?hl=ko&user=UWO1mloAAAAJ). I received my B.S. in Computer Science and Electrical Engineering from KAIST in 2022, advised by [Prof. Alice Oh](https://aliceoh9.github.io/) and [Prof. In So Kweon](http://rcv.kaist.ac.kr/index.php?mid=rcv_faculty). 
  
  During my stay in [Carnegie Mellon University](https://www.cmu.edu/), I'm working closely with [Prof. Kris Kitani](https://kriskitani.github.io/) and [Dr. Rohan Choudhury](https://rccchoudhury.github.io/).
  
  My ultimate goal is to contribute to society through AI, with a particular interest in technologies that assist the socially disadvantaged. To achieve this goal, my research mainly focuses on Computer Vision, especially on (i) 3D, and (ii) Vision-Language Models.

content:
  - title: News
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Nov 2024**: I gave a talk at the [KAIST-Google exploreCSR](https://kaistexplorecsr.github.io/2024-researchjourney) workshop as a student speaker.
      - **Aug 2024**: Settled in Pittsburgh, PA, and started my visiting scholar program at [Carnegie Mellon University](https://www.cmu.edu/)!
      - **Jun 2024**: Successfully organized the [KAIST exploreCSR](https://kaistexplorecsr.github.io/risingstars2024/) workshop, sponsored by [Google](https://research.google/programs-and-events/explorecsr/), as a workshop organizer!
      - **Jun 2024**: I am attending CVPR in person. Looking forward to seeing you in Seattle!
      - **Apr 2024**: I will be visiting [Carnegie Mellon University](https://www.cmu.edu/) starting this August. Looking forward to collaborating on projects!
      - **Feb 2024**: [UVI-Net](https://arxiv.org/abs/2404.01464) is accepted to CVPR 2024.
      - **Sep 2023**: Achieved 1st Place in the Korea Railroad Research Institute AI Competition.

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Data-Efficient Unsupervised Interpolation Without Any Intermediate Frame for 4D Medical Images** <br>
      <u>JungEun Kim</u>\*, Hangyul Yoon\*, Geondo Park, Kyungsu Kim, Eunho Yang <br>
      IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), 2024 <br>
      [paper](https://arxiv.org/abs/2404.01464) | [code](https://github.com/jungeun122333/UVI-Net)

  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Carnegie Mellon University ([CMU](https://www.cmu.edu/))** <br>
      Visiting Scholar in Computer Science <br>
      Aug. 2024 - Feb. 2025

      - **Korea Advanced Institute of Science and Technology ([KAIST](https://kaist.ac.kr/))** <br>
      Master Student in Artificial Intelligence <br>
      Sep. 2022 - Present

      - **Korea Advanced Institute of Science and Technology ([KAIST](https://kaist.ac.kr/))** <br>
      B.S. in Computer Science and Electrical Engineering (double major) <br>
      Mar. 2017 - Aug. 2022

  - title: Research Experiences
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **[Naver Cloud](https://www.navercloudcorp.com/) Computer Vision Team** <br>
      Research Intern <br>
      Sep. 2023 - Dec. 2023

      - **[Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/)** <br>
      Undergraduate Research Engineer with Scholarship <br>
      Dec. 2020 - Aug. 2022

      - **KAIST Machine Learning and Intelligence Lab ([MLILAB](https://mli.kaist.ac.kr/))** <br>
      Undergraduate Intern <br>
      Dec. 2020 - Aug. 2022

      - **KAIST Software Engineering Lab ([SELab](https://se.kaist.ac.kr/selab/))** <br>
      Undergraduate Intern <br>
      Mar. 2021 - Nov. 2021

  - title: Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Developing a virtual doctor LLM model, [AITRICS](https://www.aitrics.com/) (2024)
      - Research on the Investigation and Application of Data Augmentation, [Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/) (2022)
      - Investigation and Application of Lightweighting Techniques for Deep Learning Models, [Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/) (2021)
      - An Overview of Gradient Descent Optimization Algorithms with Applications, [Samsung Electronics](https://www.samsung.com/sec/aboutsamsung/home/) (2021)

  - title: Honors & Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Student Speaker**, KAIST-Google exploreCSR (2024)
      - **Korean Government Scholarship**, Scholarship for the Visiting Scholar Program at Carnegie Mellon University (2024)
      - **Workshop Organizer**, KAIST-Google exploreCSR \[[Link](https://research.google/programs-and-events/explorecsr/)\] (2024)
      - **1st Place**, Korea Railroad Research Institute AI Competition (2023)
      - **KAIST Government Scholarship**, Scholarship for the Master's Degree (2022-2024)
      - **Leadership Certificate**, KAIST Global Leadership Center (2022)
      - **Research Scholarship**, Samsung Electronics (2020-2022)
      - **Conference Organizer**, National Electronics Major College Student Conference (2020)
      - **Student Council Member**, KAIST Department of Electrical Engineering (2018-2019)
      - **KAIST Government Scholarship**, Scholarship for the Bachelor's Degree (2017-2022)
      - **Volunteer Service**: 200+ hours of community service (2015-Present)

  - title: Teaching Experiences
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Main Instructor**, AI Competency Enhancement Program for Industrial Professionals at [HD Hyundai](http://www.hd-hyundai.com/) (2023)
      - **Teaching Assistant**, Meachine Learning for AI at KAIST (2023)
      - **Coding Assistant**, AI Track at [Elice](https://elice.training/) (2020-2021)
      - **Career Instructor**, Korea Foundation for the Advancement of Science and Creativity ([KOSAC](https://www.kosac.re.kr/eng)) (2019-2020)
      - **Teaching Assistant**, Calculus at KAIST (2019)

  - title: Professional Services
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Journal Reviewer**: Progress in Engineering Science'24, Computers in Biology and Medicine'24, Computer Methods and Programs in Biomedicine'24

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
